//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicsNAV365_Staff_WebPortal.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://41.78.24.34:9047/CPHD/WS/CPHD/Codeunit/EmployeeAccountWebService")]
        public string DynamicsNAV365_Staff_WebPortal_EmployeeAccountWebServiceReference_EmployeeAccountWebService {
            get {
                return ((string)(this["DynamicsNAV365_Staff_WebPortal_EmployeeAccountWebServiceReference_EmployeeAccount" +
                    "WebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://41.78.24.34:9047/CPHD/WS/CPHD/Codeunit/InventoryManagementWS")]
        public string DynamicsNAV365_Staff_WebPortal_InventoryManagementWebServiceReference_InventoryManagementWS {
            get {
                return ((string)(this["DynamicsNAV365_Staff_WebPortal_InventoryManagementWebServiceReference_InventoryMa" +
                    "nagementWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://41.78.24.34:9047/CPHD/WS/CPHD/Codeunit/HumanResourceManagementWS")]
        public string DynamicsNAV365_Staff_WebPortal_HumanResourceWebServiceReference_HumanResourceManagementWS {
            get {
                return ((string)(this["DynamicsNAV365_Staff_WebPortal_HumanResourceWebServiceReference_HumanResourceMana" +
                    "gementWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://41.78.24.34:9047/CPHD/WS/CPHD/Codeunit/ProcurementManagementWS")]
        public string DynamicsNAV365_Staff_WebPortal_ProcurementManagementWebServiceReference_ProcurementManagementWS {
            get {
                return ((string)(this["DynamicsNAV365_Staff_WebPortal_ProcurementManagementWebServiceReference_Procureme" +
                    "ntManagementWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://41.78.24.34:9047/CPHD/WS/CPHD/Codeunit/FundsManagementWebService")]
        public string DynamicsNAV365_Staff_WebPortal_FundsManagementWebServiceReference_FundsManagementWebService {
            get {
                return ((string)(this["DynamicsNAV365_Staff_WebPortal_FundsManagementWebServiceReference_FundsManagement" +
                    "WebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://41.78.24.34:9047/CPHD/WS/CPHD/Codeunit/FundsClaimManagementWebService")]
        public string DynamicsNAV365_Staff_WebPortal_FundsClaimWebserviceReference_FundsClaimManagementWebService {
            get {
                return ((string)(this["DynamicsNAV365_Staff_WebPortal_FundsClaimWebserviceReference_FundsClaimManagement" +
                    "WebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://41.78.24.34:9047/CPHD/WS/CPHD/Codeunit/PortalApprovalManager")]
        public string DynamicsNAV365_Staff_WebPortal_ApprovalManagerWebServiceReference_PortalApprovalManager {
            get {
                return ((string)(this["DynamicsNAV365_Staff_WebPortal_ApprovalManagerWebServiceReference_PortalApprovalM" +
                    "anager"]));
            }
        }
    }
}
