//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace DynamicsNAV365_Staff_WebPortal.ProcurementManagementWebServiceReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ProcurementManagementWS_Binding", Namespace="urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS")]
    public partial class ProcurementManagementWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CheckPurchaseRequisitionExistsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckOpenPurchaseRequisitionExistsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreatePurchaseRequisitionOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModifyPurchaseRequisitionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPurchaseRequisitionAmountOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPurchaseRequisitionStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPurchaseRequisitionGlobalDimension1CodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPurchaseRequisitionGlobalDimension2CodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreatePurchaseRequisitionLineOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModifyPurchaseRequisitionLineOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeletePurchaseRequisitionLineOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckPurchaseRequisitionLinesExistOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidatePurchaseRequisitionLinesOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckPurchaseRequisitionApprovalWorkflowEnabledOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendPurchaseRequisitionApprovalRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelPurchaseRequisitionApprovalRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReopenPurchaseRequisitionOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckBudgetPurchaseRequisitionOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelBudgetCommitmentPurchaseRequisitionOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckIfGLAccountBlockedOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModifyProcurementUploadedDocumentLocalURLOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckProcurementUploadedDocumentAttachedOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteProcurementUploadedDocumentOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ProcurementManagementWS() {
            this.Url = global::DynamicsNAV365_Staff_WebPortal.Properties.Settings.Default.DynamicsNAV365_Staff_WebPortal_ProcurementManagementWebServiceReference_ProcurementManagementWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CheckPurchaseRequisitionExistsCompletedEventHandler CheckPurchaseRequisitionExistsCompleted;
        
        /// <remarks/>
        public event CheckOpenPurchaseRequisitionExistsCompletedEventHandler CheckOpenPurchaseRequisitionExistsCompleted;
        
        /// <remarks/>
        public event CreatePurchaseRequisitionCompletedEventHandler CreatePurchaseRequisitionCompleted;
        
        /// <remarks/>
        public event ModifyPurchaseRequisitionCompletedEventHandler ModifyPurchaseRequisitionCompleted;
        
        /// <remarks/>
        public event GetPurchaseRequisitionAmountCompletedEventHandler GetPurchaseRequisitionAmountCompleted;
        
        /// <remarks/>
        public event GetPurchaseRequisitionStatusCompletedEventHandler GetPurchaseRequisitionStatusCompleted;
        
        /// <remarks/>
        public event GetPurchaseRequisitionGlobalDimension1CodeCompletedEventHandler GetPurchaseRequisitionGlobalDimension1CodeCompleted;
        
        /// <remarks/>
        public event GetPurchaseRequisitionGlobalDimension2CodeCompletedEventHandler GetPurchaseRequisitionGlobalDimension2CodeCompleted;
        
        /// <remarks/>
        public event CreatePurchaseRequisitionLineCompletedEventHandler CreatePurchaseRequisitionLineCompleted;
        
        /// <remarks/>
        public event ModifyPurchaseRequisitionLineCompletedEventHandler ModifyPurchaseRequisitionLineCompleted;
        
        /// <remarks/>
        public event DeletePurchaseRequisitionLineCompletedEventHandler DeletePurchaseRequisitionLineCompleted;
        
        /// <remarks/>
        public event CheckPurchaseRequisitionLinesExistCompletedEventHandler CheckPurchaseRequisitionLinesExistCompleted;
        
        /// <remarks/>
        public event ValidatePurchaseRequisitionLinesCompletedEventHandler ValidatePurchaseRequisitionLinesCompleted;
        
        /// <remarks/>
        public event CheckPurchaseRequisitionApprovalWorkflowEnabledCompletedEventHandler CheckPurchaseRequisitionApprovalWorkflowEnabledCompleted;
        
        /// <remarks/>
        public event SendPurchaseRequisitionApprovalRequestCompletedEventHandler SendPurchaseRequisitionApprovalRequestCompleted;
        
        /// <remarks/>
        public event CancelPurchaseRequisitionApprovalRequestCompletedEventHandler CancelPurchaseRequisitionApprovalRequestCompleted;
        
        /// <remarks/>
        public event ReopenPurchaseRequisitionCompletedEventHandler ReopenPurchaseRequisitionCompleted;
        
        /// <remarks/>
        public event CheckBudgetPurchaseRequisitionCompletedEventHandler CheckBudgetPurchaseRequisitionCompleted;
        
        /// <remarks/>
        public event CancelBudgetCommitmentPurchaseRequisitionCompletedEventHandler CancelBudgetCommitmentPurchaseRequisitionCompleted;
        
        /// <remarks/>
        public event CheckIfGLAccountBlockedCompletedEventHandler CheckIfGLAccountBlockedCompleted;
        
        /// <remarks/>
        public event ModifyProcurementUploadedDocumentLocalURLCompletedEventHandler ModifyProcurementUploadedDocumentLocalURLCompleted;
        
        /// <remarks/>
        public event CheckProcurementUploadedDocumentAttachedCompletedEventHandler CheckProcurementUploadedDocumentAttachedCompleted;
        
        /// <remarks/>
        public event DeleteProcurementUploadedDocumentCompletedEventHandler DeleteProcurementUploadedDocumentCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS:CheckPurchaseRequ" +
            "isitionExists", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS", ResponseElementName="CheckPurchaseRequisitionExists_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool CheckPurchaseRequisitionExists(string purchaseRequisitionNoa46, string employeeNoa46) {
            object[] results = this.Invoke("CheckPurchaseRequisitionExists", new object[] {
                        purchaseRequisitionNoa46,
                        employeeNoa46});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CheckPurchaseRequisitionExistsAsync(string purchaseRequisitionNoa46, string employeeNoa46) {
            this.CheckPurchaseRequisitionExistsAsync(purchaseRequisitionNoa46, employeeNoa46, null);
        }
        
        /// <remarks/>
        public void CheckPurchaseRequisitionExistsAsync(string purchaseRequisitionNoa46, string employeeNoa46, object userState) {
            if ((this.CheckPurchaseRequisitionExistsOperationCompleted == null)) {
                this.CheckPurchaseRequisitionExistsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckPurchaseRequisitionExistsOperationCompleted);
            }
            this.InvokeAsync("CheckPurchaseRequisitionExists", new object[] {
                        purchaseRequisitionNoa46,
                        employeeNoa46}, this.CheckPurchaseRequisitionExistsOperationCompleted, userState);
        }
        
        private void OnCheckPurchaseRequisitionExistsOperationCompleted(object arg) {
            if ((this.CheckPurchaseRequisitionExistsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckPurchaseRequisitionExistsCompleted(this, new CheckPurchaseRequisitionExistsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS:CheckOpenPurchase" +
            "RequisitionExists", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS", ResponseElementName="CheckOpenPurchaseRequisitionExists_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool CheckOpenPurchaseRequisitionExists(string employeeNoa46) {
            object[] results = this.Invoke("CheckOpenPurchaseRequisitionExists", new object[] {
                        employeeNoa46});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CheckOpenPurchaseRequisitionExistsAsync(string employeeNoa46) {
            this.CheckOpenPurchaseRequisitionExistsAsync(employeeNoa46, null);
        }
        
        /// <remarks/>
        public void CheckOpenPurchaseRequisitionExistsAsync(string employeeNoa46, object userState) {
            if ((this.CheckOpenPurchaseRequisitionExistsOperationCompleted == null)) {
                this.CheckOpenPurchaseRequisitionExistsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckOpenPurchaseRequisitionExistsOperationCompleted);
            }
            this.InvokeAsync("CheckOpenPurchaseRequisitionExists", new object[] {
                        employeeNoa46}, this.CheckOpenPurchaseRequisitionExistsOperationCompleted, userState);
        }
        
        private void OnCheckOpenPurchaseRequisitionExistsOperationCompleted(object arg) {
            if ((this.CheckOpenPurchaseRequisitionExistsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckOpenPurchaseRequisitionExistsCompleted(this, new CheckOpenPurchaseRequisitionExistsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS:CreatePurchaseReq" +
            "uisition", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS", ResponseElementName="CreatePurchaseRequisition_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string CreatePurchaseRequisition(string employeeNoa46) {
            object[] results = this.Invoke("CreatePurchaseRequisition", new object[] {
                        employeeNoa46});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CreatePurchaseRequisitionAsync(string employeeNoa46) {
            this.CreatePurchaseRequisitionAsync(employeeNoa46, null);
        }
        
        /// <remarks/>
        public void CreatePurchaseRequisitionAsync(string employeeNoa46, object userState) {
            if ((this.CreatePurchaseRequisitionOperationCompleted == null)) {
                this.CreatePurchaseRequisitionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreatePurchaseRequisitionOperationCompleted);
            }
            this.InvokeAsync("CreatePurchaseRequisition", new object[] {
                        employeeNoa46}, this.CreatePurchaseRequisitionOperationCompleted, userState);
        }
        
        private void OnCreatePurchaseRequisitionOperationCompleted(object arg) {
            if ((this.CreatePurchaseRequisitionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreatePurchaseRequisitionCompleted(this, new CreatePurchaseRequisitionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS:ModifyPurchaseReq" +
            "uisition", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS", ResponseElementName="ModifyPurchaseRequisition_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool ModifyPurchaseRequisition(string purchaseRequisitionNoa46, string employeeNoa46, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime expectedReceiptDate, string description) {
            object[] results = this.Invoke("ModifyPurchaseRequisition", new object[] {
                        purchaseRequisitionNoa46,
                        employeeNoa46,
                        expectedReceiptDate,
                        description});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ModifyPurchaseRequisitionAsync(string purchaseRequisitionNoa46, string employeeNoa46, System.DateTime expectedReceiptDate, string description) {
            this.ModifyPurchaseRequisitionAsync(purchaseRequisitionNoa46, employeeNoa46, expectedReceiptDate, description, null);
        }
        
        /// <remarks/>
        public void ModifyPurchaseRequisitionAsync(string purchaseRequisitionNoa46, string employeeNoa46, System.DateTime expectedReceiptDate, string description, object userState) {
            if ((this.ModifyPurchaseRequisitionOperationCompleted == null)) {
                this.ModifyPurchaseRequisitionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModifyPurchaseRequisitionOperationCompleted);
            }
            this.InvokeAsync("ModifyPurchaseRequisition", new object[] {
                        purchaseRequisitionNoa46,
                        employeeNoa46,
                        expectedReceiptDate,
                        description}, this.ModifyPurchaseRequisitionOperationCompleted, userState);
        }
        
        private void OnModifyPurchaseRequisitionOperationCompleted(object arg) {
            if ((this.ModifyPurchaseRequisitionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModifyPurchaseRequisitionCompleted(this, new ModifyPurchaseRequisitionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS:GetPurchaseRequis" +
            "itionAmount", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS", ResponseElementName="GetPurchaseRequisitionAmount_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public decimal GetPurchaseRequisitionAmount(string purchaseRequisitionNoa46) {
            object[] results = this.Invoke("GetPurchaseRequisitionAmount", new object[] {
                        purchaseRequisitionNoa46});
            return ((decimal)(results[0]));
        }
        
        /// <remarks/>
        public void GetPurchaseRequisitionAmountAsync(string purchaseRequisitionNoa46) {
            this.GetPurchaseRequisitionAmountAsync(purchaseRequisitionNoa46, null);
        }
        
        /// <remarks/>
        public void GetPurchaseRequisitionAmountAsync(string purchaseRequisitionNoa46, object userState) {
            if ((this.GetPurchaseRequisitionAmountOperationCompleted == null)) {
                this.GetPurchaseRequisitionAmountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPurchaseRequisitionAmountOperationCompleted);
            }
            this.InvokeAsync("GetPurchaseRequisitionAmount", new object[] {
                        purchaseRequisitionNoa46}, this.GetPurchaseRequisitionAmountOperationCompleted, userState);
        }
        
        private void OnGetPurchaseRequisitionAmountOperationCompleted(object arg) {
            if ((this.GetPurchaseRequisitionAmountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPurchaseRequisitionAmountCompleted(this, new GetPurchaseRequisitionAmountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS:GetPurchaseRequis" +
            "itionStatus", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS", ResponseElementName="GetPurchaseRequisitionStatus_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetPurchaseRequisitionStatus(string purchaseRequisitionNoa46) {
            object[] results = this.Invoke("GetPurchaseRequisitionStatus", new object[] {
                        purchaseRequisitionNoa46});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetPurchaseRequisitionStatusAsync(string purchaseRequisitionNoa46) {
            this.GetPurchaseRequisitionStatusAsync(purchaseRequisitionNoa46, null);
        }
        
        /// <remarks/>
        public void GetPurchaseRequisitionStatusAsync(string purchaseRequisitionNoa46, object userState) {
            if ((this.GetPurchaseRequisitionStatusOperationCompleted == null)) {
                this.GetPurchaseRequisitionStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPurchaseRequisitionStatusOperationCompleted);
            }
            this.InvokeAsync("GetPurchaseRequisitionStatus", new object[] {
                        purchaseRequisitionNoa46}, this.GetPurchaseRequisitionStatusOperationCompleted, userState);
        }
        
        private void OnGetPurchaseRequisitionStatusOperationCompleted(object arg) {
            if ((this.GetPurchaseRequisitionStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPurchaseRequisitionStatusCompleted(this, new GetPurchaseRequisitionStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS:GetPurchaseRequis" +
            "itionGlobalDimension1Code", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS", ResponseElementName="GetPurchaseRequisitionGlobalDimension1Code_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetPurchaseRequisitionGlobalDimension1Code(string purchaseRequisitionNoa46) {
            object[] results = this.Invoke("GetPurchaseRequisitionGlobalDimension1Code", new object[] {
                        purchaseRequisitionNoa46});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetPurchaseRequisitionGlobalDimension1CodeAsync(string purchaseRequisitionNoa46) {
            this.GetPurchaseRequisitionGlobalDimension1CodeAsync(purchaseRequisitionNoa46, null);
        }
        
        /// <remarks/>
        public void GetPurchaseRequisitionGlobalDimension1CodeAsync(string purchaseRequisitionNoa46, object userState) {
            if ((this.GetPurchaseRequisitionGlobalDimension1CodeOperationCompleted == null)) {
                this.GetPurchaseRequisitionGlobalDimension1CodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPurchaseRequisitionGlobalDimension1CodeOperationCompleted);
            }
            this.InvokeAsync("GetPurchaseRequisitionGlobalDimension1Code", new object[] {
                        purchaseRequisitionNoa46}, this.GetPurchaseRequisitionGlobalDimension1CodeOperationCompleted, userState);
        }
        
        private void OnGetPurchaseRequisitionGlobalDimension1CodeOperationCompleted(object arg) {
            if ((this.GetPurchaseRequisitionGlobalDimension1CodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPurchaseRequisitionGlobalDimension1CodeCompleted(this, new GetPurchaseRequisitionGlobalDimension1CodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS:GetPurchaseRequis" +
            "itionGlobalDimension2Code", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS", ResponseElementName="GetPurchaseRequisitionGlobalDimension2Code_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetPurchaseRequisitionGlobalDimension2Code(string purchaseRequisitionNoa46) {
            object[] results = this.Invoke("GetPurchaseRequisitionGlobalDimension2Code", new object[] {
                        purchaseRequisitionNoa46});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetPurchaseRequisitionGlobalDimension2CodeAsync(string purchaseRequisitionNoa46) {
            this.GetPurchaseRequisitionGlobalDimension2CodeAsync(purchaseRequisitionNoa46, null);
        }
        
        /// <remarks/>
        public void GetPurchaseRequisitionGlobalDimension2CodeAsync(string purchaseRequisitionNoa46, object userState) {
            if ((this.GetPurchaseRequisitionGlobalDimension2CodeOperationCompleted == null)) {
                this.GetPurchaseRequisitionGlobalDimension2CodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPurchaseRequisitionGlobalDimension2CodeOperationCompleted);
            }
            this.InvokeAsync("GetPurchaseRequisitionGlobalDimension2Code", new object[] {
                        purchaseRequisitionNoa46}, this.GetPurchaseRequisitionGlobalDimension2CodeOperationCompleted, userState);
        }
        
        private void OnGetPurchaseRequisitionGlobalDimension2CodeOperationCompleted(object arg) {
            if ((this.GetPurchaseRequisitionGlobalDimension2CodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPurchaseRequisitionGlobalDimension2CodeCompleted(this, new GetPurchaseRequisitionGlobalDimension2CodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS:CreatePurchaseReq" +
            "uisitionLine", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS", ResponseElementName="CreatePurchaseRequisitionLine_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool CreatePurchaseRequisitionLine(string purchaseRequisitionNoa46, string requisitionType, string requisitionCode, int quantity, decimal unitCost, string uOM, string description) {
            object[] results = this.Invoke("CreatePurchaseRequisitionLine", new object[] {
                        purchaseRequisitionNoa46,
                        requisitionType,
                        requisitionCode,
                        quantity,
                        unitCost,
                        uOM,
                        description});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CreatePurchaseRequisitionLineAsync(string purchaseRequisitionNoa46, string requisitionType, string requisitionCode, int quantity, decimal unitCost, string uOM, string description) {
            this.CreatePurchaseRequisitionLineAsync(purchaseRequisitionNoa46, requisitionType, requisitionCode, quantity, unitCost, uOM, description, null);
        }
        
        /// <remarks/>
        public void CreatePurchaseRequisitionLineAsync(string purchaseRequisitionNoa46, string requisitionType, string requisitionCode, int quantity, decimal unitCost, string uOM, string description, object userState) {
            if ((this.CreatePurchaseRequisitionLineOperationCompleted == null)) {
                this.CreatePurchaseRequisitionLineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreatePurchaseRequisitionLineOperationCompleted);
            }
            this.InvokeAsync("CreatePurchaseRequisitionLine", new object[] {
                        purchaseRequisitionNoa46,
                        requisitionType,
                        requisitionCode,
                        quantity,
                        unitCost,
                        uOM,
                        description}, this.CreatePurchaseRequisitionLineOperationCompleted, userState);
        }
        
        private void OnCreatePurchaseRequisitionLineOperationCompleted(object arg) {
            if ((this.CreatePurchaseRequisitionLineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreatePurchaseRequisitionLineCompleted(this, new CreatePurchaseRequisitionLineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS:ModifyPurchaseReq" +
            "uisitionLine", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS", ResponseElementName="ModifyPurchaseRequisitionLine_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool ModifyPurchaseRequisitionLine(int lineNoa46, string purchaseRequisitionNoa46, string requisitionType, string requisitionCode, int quantity, decimal unitCost, string uOM, string description) {
            object[] results = this.Invoke("ModifyPurchaseRequisitionLine", new object[] {
                        lineNoa46,
                        purchaseRequisitionNoa46,
                        requisitionType,
                        requisitionCode,
                        quantity,
                        unitCost,
                        uOM,
                        description});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ModifyPurchaseRequisitionLineAsync(int lineNoa46, string purchaseRequisitionNoa46, string requisitionType, string requisitionCode, int quantity, decimal unitCost, string uOM, string description) {
            this.ModifyPurchaseRequisitionLineAsync(lineNoa46, purchaseRequisitionNoa46, requisitionType, requisitionCode, quantity, unitCost, uOM, description, null);
        }
        
        /// <remarks/>
        public void ModifyPurchaseRequisitionLineAsync(int lineNoa46, string purchaseRequisitionNoa46, string requisitionType, string requisitionCode, int quantity, decimal unitCost, string uOM, string description, object userState) {
            if ((this.ModifyPurchaseRequisitionLineOperationCompleted == null)) {
                this.ModifyPurchaseRequisitionLineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModifyPurchaseRequisitionLineOperationCompleted);
            }
            this.InvokeAsync("ModifyPurchaseRequisitionLine", new object[] {
                        lineNoa46,
                        purchaseRequisitionNoa46,
                        requisitionType,
                        requisitionCode,
                        quantity,
                        unitCost,
                        uOM,
                        description}, this.ModifyPurchaseRequisitionLineOperationCompleted, userState);
        }
        
        private void OnModifyPurchaseRequisitionLineOperationCompleted(object arg) {
            if ((this.ModifyPurchaseRequisitionLineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModifyPurchaseRequisitionLineCompleted(this, new ModifyPurchaseRequisitionLineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS:DeletePurchaseReq" +
            "uisitionLine", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS", ResponseElementName="DeletePurchaseRequisitionLine_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool DeletePurchaseRequisitionLine(int lineNoa46, string purchaseRequisitionNoa46) {
            object[] results = this.Invoke("DeletePurchaseRequisitionLine", new object[] {
                        lineNoa46,
                        purchaseRequisitionNoa46});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeletePurchaseRequisitionLineAsync(int lineNoa46, string purchaseRequisitionNoa46) {
            this.DeletePurchaseRequisitionLineAsync(lineNoa46, purchaseRequisitionNoa46, null);
        }
        
        /// <remarks/>
        public void DeletePurchaseRequisitionLineAsync(int lineNoa46, string purchaseRequisitionNoa46, object userState) {
            if ((this.DeletePurchaseRequisitionLineOperationCompleted == null)) {
                this.DeletePurchaseRequisitionLineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeletePurchaseRequisitionLineOperationCompleted);
            }
            this.InvokeAsync("DeletePurchaseRequisitionLine", new object[] {
                        lineNoa46,
                        purchaseRequisitionNoa46}, this.DeletePurchaseRequisitionLineOperationCompleted, userState);
        }
        
        private void OnDeletePurchaseRequisitionLineOperationCompleted(object arg) {
            if ((this.DeletePurchaseRequisitionLineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeletePurchaseRequisitionLineCompleted(this, new DeletePurchaseRequisitionLineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS:CheckPurchaseRequ" +
            "isitionLinesExist", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS", ResponseElementName="CheckPurchaseRequisitionLinesExist_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool CheckPurchaseRequisitionLinesExist(string purchaseRequisitionNoa46) {
            object[] results = this.Invoke("CheckPurchaseRequisitionLinesExist", new object[] {
                        purchaseRequisitionNoa46});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CheckPurchaseRequisitionLinesExistAsync(string purchaseRequisitionNoa46) {
            this.CheckPurchaseRequisitionLinesExistAsync(purchaseRequisitionNoa46, null);
        }
        
        /// <remarks/>
        public void CheckPurchaseRequisitionLinesExistAsync(string purchaseRequisitionNoa46, object userState) {
            if ((this.CheckPurchaseRequisitionLinesExistOperationCompleted == null)) {
                this.CheckPurchaseRequisitionLinesExistOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckPurchaseRequisitionLinesExistOperationCompleted);
            }
            this.InvokeAsync("CheckPurchaseRequisitionLinesExist", new object[] {
                        purchaseRequisitionNoa46}, this.CheckPurchaseRequisitionLinesExistOperationCompleted, userState);
        }
        
        private void OnCheckPurchaseRequisitionLinesExistOperationCompleted(object arg) {
            if ((this.CheckPurchaseRequisitionLinesExistCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckPurchaseRequisitionLinesExistCompleted(this, new CheckPurchaseRequisitionLinesExistCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS:ValidatePurchaseR" +
            "equisitionLines", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS", ResponseElementName="ValidatePurchaseRequisitionLines_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string ValidatePurchaseRequisitionLines(string purchaseRequisitionNoa46) {
            object[] results = this.Invoke("ValidatePurchaseRequisitionLines", new object[] {
                        purchaseRequisitionNoa46});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ValidatePurchaseRequisitionLinesAsync(string purchaseRequisitionNoa46) {
            this.ValidatePurchaseRequisitionLinesAsync(purchaseRequisitionNoa46, null);
        }
        
        /// <remarks/>
        public void ValidatePurchaseRequisitionLinesAsync(string purchaseRequisitionNoa46, object userState) {
            if ((this.ValidatePurchaseRequisitionLinesOperationCompleted == null)) {
                this.ValidatePurchaseRequisitionLinesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidatePurchaseRequisitionLinesOperationCompleted);
            }
            this.InvokeAsync("ValidatePurchaseRequisitionLines", new object[] {
                        purchaseRequisitionNoa46}, this.ValidatePurchaseRequisitionLinesOperationCompleted, userState);
        }
        
        private void OnValidatePurchaseRequisitionLinesOperationCompleted(object arg) {
            if ((this.ValidatePurchaseRequisitionLinesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidatePurchaseRequisitionLinesCompleted(this, new ValidatePurchaseRequisitionLinesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS:CheckPurchaseRequ" +
            "isitionApprovalWorkflowEnabled", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS", ResponseElementName="CheckPurchaseRequisitionApprovalWorkflowEnabled_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool CheckPurchaseRequisitionApprovalWorkflowEnabled(string purchaseRequisitionNoa46) {
            object[] results = this.Invoke("CheckPurchaseRequisitionApprovalWorkflowEnabled", new object[] {
                        purchaseRequisitionNoa46});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CheckPurchaseRequisitionApprovalWorkflowEnabledAsync(string purchaseRequisitionNoa46) {
            this.CheckPurchaseRequisitionApprovalWorkflowEnabledAsync(purchaseRequisitionNoa46, null);
        }
        
        /// <remarks/>
        public void CheckPurchaseRequisitionApprovalWorkflowEnabledAsync(string purchaseRequisitionNoa46, object userState) {
            if ((this.CheckPurchaseRequisitionApprovalWorkflowEnabledOperationCompleted == null)) {
                this.CheckPurchaseRequisitionApprovalWorkflowEnabledOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckPurchaseRequisitionApprovalWorkflowEnabledOperationCompleted);
            }
            this.InvokeAsync("CheckPurchaseRequisitionApprovalWorkflowEnabled", new object[] {
                        purchaseRequisitionNoa46}, this.CheckPurchaseRequisitionApprovalWorkflowEnabledOperationCompleted, userState);
        }
        
        private void OnCheckPurchaseRequisitionApprovalWorkflowEnabledOperationCompleted(object arg) {
            if ((this.CheckPurchaseRequisitionApprovalWorkflowEnabledCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckPurchaseRequisitionApprovalWorkflowEnabledCompleted(this, new CheckPurchaseRequisitionApprovalWorkflowEnabledCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS:SendPurchaseRequi" +
            "sitionApprovalRequest", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS", ResponseElementName="SendPurchaseRequisitionApprovalRequest_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool SendPurchaseRequisitionApprovalRequest(string purchaseRequisitionNoa46) {
            object[] results = this.Invoke("SendPurchaseRequisitionApprovalRequest", new object[] {
                        purchaseRequisitionNoa46});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SendPurchaseRequisitionApprovalRequestAsync(string purchaseRequisitionNoa46) {
            this.SendPurchaseRequisitionApprovalRequestAsync(purchaseRequisitionNoa46, null);
        }
        
        /// <remarks/>
        public void SendPurchaseRequisitionApprovalRequestAsync(string purchaseRequisitionNoa46, object userState) {
            if ((this.SendPurchaseRequisitionApprovalRequestOperationCompleted == null)) {
                this.SendPurchaseRequisitionApprovalRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendPurchaseRequisitionApprovalRequestOperationCompleted);
            }
            this.InvokeAsync("SendPurchaseRequisitionApprovalRequest", new object[] {
                        purchaseRequisitionNoa46}, this.SendPurchaseRequisitionApprovalRequestOperationCompleted, userState);
        }
        
        private void OnSendPurchaseRequisitionApprovalRequestOperationCompleted(object arg) {
            if ((this.SendPurchaseRequisitionApprovalRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendPurchaseRequisitionApprovalRequestCompleted(this, new SendPurchaseRequisitionApprovalRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS:CancelPurchaseReq" +
            "uisitionApprovalRequest", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS", ResponseElementName="CancelPurchaseRequisitionApprovalRequest_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool CancelPurchaseRequisitionApprovalRequest(string purchaseRequisitionNoa46) {
            object[] results = this.Invoke("CancelPurchaseRequisitionApprovalRequest", new object[] {
                        purchaseRequisitionNoa46});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CancelPurchaseRequisitionApprovalRequestAsync(string purchaseRequisitionNoa46) {
            this.CancelPurchaseRequisitionApprovalRequestAsync(purchaseRequisitionNoa46, null);
        }
        
        /// <remarks/>
        public void CancelPurchaseRequisitionApprovalRequestAsync(string purchaseRequisitionNoa46, object userState) {
            if ((this.CancelPurchaseRequisitionApprovalRequestOperationCompleted == null)) {
                this.CancelPurchaseRequisitionApprovalRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelPurchaseRequisitionApprovalRequestOperationCompleted);
            }
            this.InvokeAsync("CancelPurchaseRequisitionApprovalRequest", new object[] {
                        purchaseRequisitionNoa46}, this.CancelPurchaseRequisitionApprovalRequestOperationCompleted, userState);
        }
        
        private void OnCancelPurchaseRequisitionApprovalRequestOperationCompleted(object arg) {
            if ((this.CancelPurchaseRequisitionApprovalRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelPurchaseRequisitionApprovalRequestCompleted(this, new CancelPurchaseRequisitionApprovalRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS:ReopenPurchaseReq" +
            "uisition", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS", ResponseElementName="ReopenPurchaseRequisition_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool ReopenPurchaseRequisition(string purchaseRequisitionNoa46) {
            object[] results = this.Invoke("ReopenPurchaseRequisition", new object[] {
                        purchaseRequisitionNoa46});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ReopenPurchaseRequisitionAsync(string purchaseRequisitionNoa46) {
            this.ReopenPurchaseRequisitionAsync(purchaseRequisitionNoa46, null);
        }
        
        /// <remarks/>
        public void ReopenPurchaseRequisitionAsync(string purchaseRequisitionNoa46, object userState) {
            if ((this.ReopenPurchaseRequisitionOperationCompleted == null)) {
                this.ReopenPurchaseRequisitionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReopenPurchaseRequisitionOperationCompleted);
            }
            this.InvokeAsync("ReopenPurchaseRequisition", new object[] {
                        purchaseRequisitionNoa46}, this.ReopenPurchaseRequisitionOperationCompleted, userState);
        }
        
        private void OnReopenPurchaseRequisitionOperationCompleted(object arg) {
            if ((this.ReopenPurchaseRequisitionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReopenPurchaseRequisitionCompleted(this, new ReopenPurchaseRequisitionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS:CheckBudgetPurcha" +
            "seRequisition", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS", ResponseElementName="CheckBudgetPurchaseRequisition_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CheckBudgetPurchaseRequisition(string purchReqNo, [System.Xml.Serialization.XmlElementAttribute(DataType="date")] System.DateTime documentDate) {
            this.Invoke("CheckBudgetPurchaseRequisition", new object[] {
                        purchReqNo,
                        documentDate});
        }
        
        /// <remarks/>
        public void CheckBudgetPurchaseRequisitionAsync(string purchReqNo, System.DateTime documentDate) {
            this.CheckBudgetPurchaseRequisitionAsync(purchReqNo, documentDate, null);
        }
        
        /// <remarks/>
        public void CheckBudgetPurchaseRequisitionAsync(string purchReqNo, System.DateTime documentDate, object userState) {
            if ((this.CheckBudgetPurchaseRequisitionOperationCompleted == null)) {
                this.CheckBudgetPurchaseRequisitionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckBudgetPurchaseRequisitionOperationCompleted);
            }
            this.InvokeAsync("CheckBudgetPurchaseRequisition", new object[] {
                        purchReqNo,
                        documentDate}, this.CheckBudgetPurchaseRequisitionOperationCompleted, userState);
        }
        
        private void OnCheckBudgetPurchaseRequisitionOperationCompleted(object arg) {
            if ((this.CheckBudgetPurchaseRequisitionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckBudgetPurchaseRequisitionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS:CancelBudgetCommi" +
            "tmentPurchaseRequisition", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS", ResponseElementName="CancelBudgetCommitmentPurchaseRequisition_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CancelBudgetCommitmentPurchaseRequisition(string purchReqNo) {
            this.Invoke("CancelBudgetCommitmentPurchaseRequisition", new object[] {
                        purchReqNo});
        }
        
        /// <remarks/>
        public void CancelBudgetCommitmentPurchaseRequisitionAsync(string purchReqNo) {
            this.CancelBudgetCommitmentPurchaseRequisitionAsync(purchReqNo, null);
        }
        
        /// <remarks/>
        public void CancelBudgetCommitmentPurchaseRequisitionAsync(string purchReqNo, object userState) {
            if ((this.CancelBudgetCommitmentPurchaseRequisitionOperationCompleted == null)) {
                this.CancelBudgetCommitmentPurchaseRequisitionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelBudgetCommitmentPurchaseRequisitionOperationCompleted);
            }
            this.InvokeAsync("CancelBudgetCommitmentPurchaseRequisition", new object[] {
                        purchReqNo}, this.CancelBudgetCommitmentPurchaseRequisitionOperationCompleted, userState);
        }
        
        private void OnCancelBudgetCommitmentPurchaseRequisitionOperationCompleted(object arg) {
            if ((this.CancelBudgetCommitmentPurchaseRequisitionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelBudgetCommitmentPurchaseRequisitionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS:CheckIfGLAccountB" +
            "locked", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS", ResponseElementName="CheckIfGLAccountBlocked_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CheckIfGLAccountBlocked(string budgetName) {
            this.Invoke("CheckIfGLAccountBlocked", new object[] {
                        budgetName});
        }
        
        /// <remarks/>
        public void CheckIfGLAccountBlockedAsync(string budgetName) {
            this.CheckIfGLAccountBlockedAsync(budgetName, null);
        }
        
        /// <remarks/>
        public void CheckIfGLAccountBlockedAsync(string budgetName, object userState) {
            if ((this.CheckIfGLAccountBlockedOperationCompleted == null)) {
                this.CheckIfGLAccountBlockedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckIfGLAccountBlockedOperationCompleted);
            }
            this.InvokeAsync("CheckIfGLAccountBlocked", new object[] {
                        budgetName}, this.CheckIfGLAccountBlockedOperationCompleted, userState);
        }
        
        private void OnCheckIfGLAccountBlockedOperationCompleted(object arg) {
            if ((this.CheckIfGLAccountBlockedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckIfGLAccountBlockedCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS:ModifyProcurement" +
            "UploadedDocumentLocalURL", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS", ResponseElementName="ModifyProcurementUploadedDocumentLocalURL_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool ModifyProcurementUploadedDocumentLocalURL(string documentNoa46, string documentCode, string localURL) {
            object[] results = this.Invoke("ModifyProcurementUploadedDocumentLocalURL", new object[] {
                        documentNoa46,
                        documentCode,
                        localURL});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ModifyProcurementUploadedDocumentLocalURLAsync(string documentNoa46, string documentCode, string localURL) {
            this.ModifyProcurementUploadedDocumentLocalURLAsync(documentNoa46, documentCode, localURL, null);
        }
        
        /// <remarks/>
        public void ModifyProcurementUploadedDocumentLocalURLAsync(string documentNoa46, string documentCode, string localURL, object userState) {
            if ((this.ModifyProcurementUploadedDocumentLocalURLOperationCompleted == null)) {
                this.ModifyProcurementUploadedDocumentLocalURLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModifyProcurementUploadedDocumentLocalURLOperationCompleted);
            }
            this.InvokeAsync("ModifyProcurementUploadedDocumentLocalURL", new object[] {
                        documentNoa46,
                        documentCode,
                        localURL}, this.ModifyProcurementUploadedDocumentLocalURLOperationCompleted, userState);
        }
        
        private void OnModifyProcurementUploadedDocumentLocalURLOperationCompleted(object arg) {
            if ((this.ModifyProcurementUploadedDocumentLocalURLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModifyProcurementUploadedDocumentLocalURLCompleted(this, new ModifyProcurementUploadedDocumentLocalURLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS:CheckProcurementU" +
            "ploadedDocumentAttached", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS", ResponseElementName="CheckProcurementUploadedDocumentAttached_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool CheckProcurementUploadedDocumentAttached(string documentNoa46) {
            object[] results = this.Invoke("CheckProcurementUploadedDocumentAttached", new object[] {
                        documentNoa46});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CheckProcurementUploadedDocumentAttachedAsync(string documentNoa46) {
            this.CheckProcurementUploadedDocumentAttachedAsync(documentNoa46, null);
        }
        
        /// <remarks/>
        public void CheckProcurementUploadedDocumentAttachedAsync(string documentNoa46, object userState) {
            if ((this.CheckProcurementUploadedDocumentAttachedOperationCompleted == null)) {
                this.CheckProcurementUploadedDocumentAttachedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckProcurementUploadedDocumentAttachedOperationCompleted);
            }
            this.InvokeAsync("CheckProcurementUploadedDocumentAttached", new object[] {
                        documentNoa46}, this.CheckProcurementUploadedDocumentAttachedOperationCompleted, userState);
        }
        
        private void OnCheckProcurementUploadedDocumentAttachedOperationCompleted(object arg) {
            if ((this.CheckProcurementUploadedDocumentAttachedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckProcurementUploadedDocumentAttachedCompleted(this, new CheckProcurementUploadedDocumentAttachedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS:DeleteProcurement" +
            "UploadedDocument", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS", ResponseElementName="DeleteProcurementUploadedDocument_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/ProcurementManagementWS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public bool DeleteProcurementUploadedDocument(string documentNoa46) {
            object[] results = this.Invoke("DeleteProcurementUploadedDocument", new object[] {
                        documentNoa46});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteProcurementUploadedDocumentAsync(string documentNoa46) {
            this.DeleteProcurementUploadedDocumentAsync(documentNoa46, null);
        }
        
        /// <remarks/>
        public void DeleteProcurementUploadedDocumentAsync(string documentNoa46, object userState) {
            if ((this.DeleteProcurementUploadedDocumentOperationCompleted == null)) {
                this.DeleteProcurementUploadedDocumentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteProcurementUploadedDocumentOperationCompleted);
            }
            this.InvokeAsync("DeleteProcurementUploadedDocument", new object[] {
                        documentNoa46}, this.DeleteProcurementUploadedDocumentOperationCompleted, userState);
        }
        
        private void OnDeleteProcurementUploadedDocumentOperationCompleted(object arg) {
            if ((this.DeleteProcurementUploadedDocumentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteProcurementUploadedDocumentCompleted(this, new DeleteProcurementUploadedDocumentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void CheckPurchaseRequisitionExistsCompletedEventHandler(object sender, CheckPurchaseRequisitionExistsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckPurchaseRequisitionExistsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckPurchaseRequisitionExistsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void CheckOpenPurchaseRequisitionExistsCompletedEventHandler(object sender, CheckOpenPurchaseRequisitionExistsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckOpenPurchaseRequisitionExistsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckOpenPurchaseRequisitionExistsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void CreatePurchaseRequisitionCompletedEventHandler(object sender, CreatePurchaseRequisitionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreatePurchaseRequisitionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreatePurchaseRequisitionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ModifyPurchaseRequisitionCompletedEventHandler(object sender, ModifyPurchaseRequisitionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ModifyPurchaseRequisitionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ModifyPurchaseRequisitionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetPurchaseRequisitionAmountCompletedEventHandler(object sender, GetPurchaseRequisitionAmountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPurchaseRequisitionAmountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPurchaseRequisitionAmountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public decimal Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((decimal)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetPurchaseRequisitionStatusCompletedEventHandler(object sender, GetPurchaseRequisitionStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPurchaseRequisitionStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPurchaseRequisitionStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetPurchaseRequisitionGlobalDimension1CodeCompletedEventHandler(object sender, GetPurchaseRequisitionGlobalDimension1CodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPurchaseRequisitionGlobalDimension1CodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPurchaseRequisitionGlobalDimension1CodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetPurchaseRequisitionGlobalDimension2CodeCompletedEventHandler(object sender, GetPurchaseRequisitionGlobalDimension2CodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPurchaseRequisitionGlobalDimension2CodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPurchaseRequisitionGlobalDimension2CodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void CreatePurchaseRequisitionLineCompletedEventHandler(object sender, CreatePurchaseRequisitionLineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreatePurchaseRequisitionLineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreatePurchaseRequisitionLineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ModifyPurchaseRequisitionLineCompletedEventHandler(object sender, ModifyPurchaseRequisitionLineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ModifyPurchaseRequisitionLineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ModifyPurchaseRequisitionLineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void DeletePurchaseRequisitionLineCompletedEventHandler(object sender, DeletePurchaseRequisitionLineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeletePurchaseRequisitionLineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeletePurchaseRequisitionLineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void CheckPurchaseRequisitionLinesExistCompletedEventHandler(object sender, CheckPurchaseRequisitionLinesExistCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckPurchaseRequisitionLinesExistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckPurchaseRequisitionLinesExistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ValidatePurchaseRequisitionLinesCompletedEventHandler(object sender, ValidatePurchaseRequisitionLinesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidatePurchaseRequisitionLinesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidatePurchaseRequisitionLinesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void CheckPurchaseRequisitionApprovalWorkflowEnabledCompletedEventHandler(object sender, CheckPurchaseRequisitionApprovalWorkflowEnabledCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckPurchaseRequisitionApprovalWorkflowEnabledCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckPurchaseRequisitionApprovalWorkflowEnabledCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void SendPurchaseRequisitionApprovalRequestCompletedEventHandler(object sender, SendPurchaseRequisitionApprovalRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendPurchaseRequisitionApprovalRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendPurchaseRequisitionApprovalRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void CancelPurchaseRequisitionApprovalRequestCompletedEventHandler(object sender, CancelPurchaseRequisitionApprovalRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelPurchaseRequisitionApprovalRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelPurchaseRequisitionApprovalRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ReopenPurchaseRequisitionCompletedEventHandler(object sender, ReopenPurchaseRequisitionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReopenPurchaseRequisitionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReopenPurchaseRequisitionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void CheckBudgetPurchaseRequisitionCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void CancelBudgetCommitmentPurchaseRequisitionCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void CheckIfGLAccountBlockedCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ModifyProcurementUploadedDocumentLocalURLCompletedEventHandler(object sender, ModifyProcurementUploadedDocumentLocalURLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ModifyProcurementUploadedDocumentLocalURLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ModifyProcurementUploadedDocumentLocalURLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void CheckProcurementUploadedDocumentAttachedCompletedEventHandler(object sender, CheckProcurementUploadedDocumentAttachedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckProcurementUploadedDocumentAttachedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckProcurementUploadedDocumentAttachedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void DeleteProcurementUploadedDocumentCompletedEventHandler(object sender, DeleteProcurementUploadedDocumentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteProcurementUploadedDocumentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteProcurementUploadedDocumentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591